version: '3'
services:
  dash:
    build: .
    restart: always
    env_file: .env
    ports:
      - "4080:4080"
    volumes:
      - .:/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"